openapi: 3.0.0
info:
  title: job-dev-backend-interview
  version: '1.0'
  description: Referência da API para o desafio Goomer
  contact:
    name: Gabriel Dissotti
    url: 'https://www.linkedin.com/in/gabrieldissotti/'
    email: gabrieldnrodrigues@gmail.com
  license:
    name: Apache 2.0
    url: 'https://github.com/gabrieldissotti/job-dev-backend-interview/blob/master/LICENSE'
servers:
  - url: 'http://localhost:3333'
paths:
  /restaurants:
    get:
      summary: List Restaurants
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination:
                    type: object
                    properties:
                      page:
                        type: number
                      totalPages:
                        type: number
                      pagesize:
                        type: number
                      totalItems:
                        type: number
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Restaurant'
              examples:
                success example:
                  value:
                    pagination:
                      page: 1
                      totalPages: 1
                      pagesize: 10
                      totalItems: 1
                    items:
                      - id: e3a49cd9-64bb-428c-ac93-9e0b2f6b5da8
                        name: Gabe Panquecaria
                        photoUrl: 'https://avatars.githubusercontent.com/u/33178519?v=4'
                        createdAt: '2021-07-01T22:57:23.937Z'
                        updatedAt: '2021-07-01T22:57:23.937Z'
      operationId: get-restaurants
      description: List restaurants
      parameters:
        - schema:
            type: integer
          in: query
          name: page
          description: ''
        - schema:
            type: integer
          in: query
          name: pagesize
    post:
      summary: ''
      operationId: post-restaurants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductAndRelationships'
              examples:
                example-1:
                  value:
                    id: e3a49cd9-64bb-428c-ac93-9e0b2f6b5da8
                    name: Gabe Panquecaria
                    photoUrl: 'https://avatars.githubusercontent.com/u/33178519?v=4'
                    createdAt: '2021-07-01T22:57:23.937Z'
                    updatedAt: '2021-07-01T22:57:23.937Z'
                    address:
                      id: 24dd70b1-07bc-4abc-8d34-8841518b3598
                      street: Rua Voluntários da Patria
                      number: '371'
                      postalCode: '18060005'
                      neighborhood: Vila Carvalho
                      restaurantId: e3a49cd9-64bb-428c-ac93-9e0b2f6b5da8
                      createdAt: '2021-07-01T22:57:23.952Z'
                      updatedAt: '2021-07-01T22:57:23.952Z'
                    workingHours:
                      - id: c430dce1-0d13-435a-be91-93049bf16b2d
                        weekday: sunday
                        startAt: '13:00:00'
                        finishAt: '18:00:00'
                        restaurantId: e3a49cd9-64bb-428c-ac93-9e0b2f6b5da8
                        promotionId: null
                        createdAt: '2021-07-01T22:57:23.969Z'
                        updatedAt: '2021-07-01T22:57:23.969Z'
                      - id: 80febd35-a60c-403c-93fb-5afa2322bf21
                        weekday: saturday
                        startAt: '19:00:00'
                        finishAt: '23:58:00'
                        restaurantId: e3a49cd9-64bb-428c-ac93-9e0b2f6b5da8
                        promotionId: null
                        createdAt: '2021-07-01T22:57:23.969Z'
                        updatedAt: '2021-07-01T22:57:23.969Z'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpException'
              examples:
                duplicated weekday:
                  value:
                    status: 400
                    message: weekday sunday is duplicated in request body
                invalid weekday:
                  value:
                    status: 400
                    message: weekday sundays does not exists
                invalid time format:
                  value:
                    status: 400
                    message: 'time format to working hour in startAt is wrong. The pattern allowed is hh:mm and between 00:00 and 23:59'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpException'
              examples:
                internal server error:
                  value:
                    status: 500
                    message: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrUpdateProduct'
        description: ''
  '/restaurants/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Show Restaurant
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductAndRelationships'
              examples:
                success example:
                  value:
                    id: ee9260ca-8356-4ecf-8874-50606e6816fd
                    name: Gabe Panquecaria
                    photo_url: 'https://avatars.githubusercontent.com/u/33178519?v=4'
                    createdAt: '2021-07-01T06:45:45.409Z'
                    updatedAt: '2021-07-01T06:45:45.409Z'
                    address:
                      id: 604d1249-a629-48f4-bf7e-ec455287d5b2
                      restaurantId: ee9260ca-8356-4ecf-8874-50606e6816fd
                      street: Rua Voluntários da Patria
                      number: '371'
                      postalCode: '18060005'
                      neighborhood: Vila Carvalho
                      createdAt: '2021-07-01T06:45:45.428Z'
                      updatedAt: '2021-07-01T06:45:45.428Z'
                    workingHours:
                      - id: af428bef-c927-42ad-8f27-8e9889eb34dc
                        restaurantId: ee9260ca-8356-4ecf-8874-50606e6816fd
                        promotionId: null
                        weekday: sunday
                        startAt: '13:00:00'
                        finishAt: '18:00:00'
                        createdAt: '2021-07-01T06:45:45.445Z'
                        updatedAt: '2021-07-01T06:45:45.445Z'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpException'
              examples:
                required working hours:
                  value:
                    status: 400
                    message: Promotion cant be created without working hours/weekdays
                invalid json:
                  value:
                    status: 400
                    message: 'Unexpected token } in JSON at position 278'
                invalid json 2:
                  value:
                    status: 400
                    message: Unexpected end of JSON input
                required price:
                  value:
                    status: 400
                    message: promotion.price is a required field
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpException'
              examples:
                internal server error:
                  value:
                    status: 500
                    message: Internal Server Error
      operationId: get-restaurants-id
components:
  schemas:
    Address:
      title: Address
      type: object
      x-examples:
        full:
          id: 604d1249-a629-48f4-bf7e-ec455287d5b2
          restaurant_id: ee9260ca-8356-4ecf-8874-50606e6816fd
          street: Rua Voluntários da Patria
          number: '371'
          postal_code: '18060005'
          neighborhood: Vila Carvalho
          created_at: '2021-07-01T06:45:45.428Z'
          updated_at: '2021-07-01T06:45:45.428Z'
      description: ''
      properties:
        id:
          type: string
        restaurantId:
          type: string
        street:
          type: string
        number:
          type: string
        postalCode:
          type: string
        neighborhood:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    WorkingHour:
      title: WorkingHour
      type: object
      properties:
        id:
          type: string
        restaurantId:
          type:
            - string
            - 'null'
        promotionId:
          type:
            - string
            - 'null'
        weekday:
          type: string
        startAt:
          type: string
        finishAt:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    Restaurant:
      title: Restaurant
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        photoUrl:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    Product:
      title: Product
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        photoUrl:
          type: string
        price:
          type: number
        categoryId:
          type: string
        restaurantId:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    Promotion:
      title: Promotion
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        price:
          type: number
        createdAt:
          type: string
        updatedAt:
          type: string
    ProductAndRelationships:
      title: ProductAndRelationships
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        photoUrl:
          type: string
        price:
          type: number
        categoryId:
          type: string
        restaurantId:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        promotion:
          type: object
          properties:
            id:
              type: string
            description:
              type: string
            price:
              type: number
            createdAt:
              type: string
            updatedAt:
              type: string
            workingHours:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  weekday:
                    type: string
                  startAt:
                    type: string
                  finishAt:
                    type: string
                  restaurantId:
                    type:
                      - string
                      - 'null'
                  promotionId:
                    type:
                      - string
                      - 'null'
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
    HttpException:
      title: HttpException
      type: object
      properties:
        status:
          type: number
        message:
          type: string
    CreateOrUpdateProduct:
      title: CreateOrUpdateProduct
      type: object
      properties:
        name:
          type: string
        photoUrl:
          type: string
        price:
          type: number
        categoryId:
          type: string
        restaurantId:
          type: string
        promotion:
          type: object
          properties:
            description:
              type: string
            price:
              type: number
            workingHours:
              type: array
              items:
                type: object
                properties:
                  weekday:
                    type: string
                  startAt:
                    type: string
                  finishAt:
                    type: string
                  restaurantId:
                    type:
                      - string
                      - 'null'
                  promotionId:
                    type:
                      - string
                      - 'null'
